<footer id="footer" class="footer">
	<div class="container">
		<div class="row">

			<div class="col-md-offset-3 col-md-3 col-sm-6 col-xs-12 wow fadeInUp animated" data-wow-duration="500ms">
				<div class="footer-single">
					{{-- <img src="{{ @asset('rawThemes/brandi/img/footer-logo.png')}}" alt=""> --}}
					<h2 id="logo" style="padding-top: 10px;">
					    High<strong>Winds</strong>
					    {{-- <img height="27px" src="{{ @asset('rawThemes/brandi/img/logo.png')}}" alt="Brandi"> --}}
					</h2>
					<p>is a monitoring platform that built on IoT that is used for monitoring the electrical power generated by Wind-Turbine on the Highways, with climatic monitoring as well. We also provide predictive analysis based on Machine Learning for our users.</p>
				</div>
			</div>

			<div class="col-md-3 col-sm-6 col-xs-12 wow fadeInUp animated" data-wow-duration="500ms" data-wow-delay="600ms">
				<div class="footer-single">
					<h6>Explore</h6>
					<ul>
						<li><a href="#">Inside Us</a></li>
						<li><a href="#">Flickr</a></li>
						<li><a href="#">Google</a></li>
						<li><a href="#">Forum</a></li>
					</ul>
				</div>
			</div>

			<div class="col-md-3 col-sm-6 col-xs-12 wow fadeInUp animated" data-wow-duration="500ms" data-wow-delay="900ms">
				<div class="footer-single">
					<h6>Support</h6>
					<ul>
						<li><a href="#">Contact Us</a></li>
						<li><a href="#">Market Blog</a></li>
						<li><a href="#">Help Center</a></li>
						<li><a href="#">Pressroom</a></li>
					</ul>
				</div>
			</div>

		</div>
		<div class="row">
			<div class="col-md-12">
				<p class="copyright text-center">
					Copyright © 2018 <a href="{{ @url('http://highwinds.herokuapp.com') }}">HighWinds</a>. All rights reserved. Designed & developed by <a href="{{ @url('http://highwinds.herokuapp.com/#team') }}">HighWinds</a>
				</p>
			</div>
		</div>
	</div>
</footer>